// from https://www.geeksforgeeks.org/bnf-notation-in-compiler-design/

floatnumber   ::=  pointfloat | exponentfloat
;
pointfloat    ::=  [intpart] fraction | intpart "."
;
exponentfloat ::=  (intpart | pointfloat) exponent
;
intpart       ::=  digit+
;
fraction      ::=  "." digit+
;
exponent      ::=  ("e" | "E") ["+" | "-"] digit+
;
