// from https://cs61.seas.harvard.edu/site/2020/BNFGrammars/

commandline ::= list
          |  list ";"
          |  list "&"
;
list     ::=  conditional
          |   list ";" conditional
          |   list "&" conditional
;
conditional ::=  pipeline
          |   conditional "&&" pipeline
          |   conditional "||" pipeline
;
pipeline ::=  command
          |   pipeline "|" command
;
command  ::=  word
          |   redirection
          |   command word
          |   command redirection
;
redirection  ::=  redirectionop filename
;
redirectionop  ::=  "<"  |  ">"  |  "2>"
;
